#!/bin/sh

dir=$(dirname "$0")
if [ ! -d "$dir"/upload-images ]
then 
  mkdir "$dir"/upload-images
  [ $? = 1 ] && exit 3
fi

php --php-ini /usr/share/php5/php.ini-development -S $(ip a | grep inet' ' | tail -n1 |cut -d' ' -f6 | cut -d/ -f1):8000 -t "$(dirname $0)"
